### ISSUE TITLE
Error when installing Seurat.utils

### ISSUE THREAD

**Issue by OliverEichmueller** [vertesy/Seurat.utils#42]
Hey Abel,

I loaded all packages w/o problems, except for Seurat.utils

Gave the following error message:
>Error: object ‘Stringendo::percentage_formatter’ is not exported by 'namespace:Stringendo'

**Comment by vertesy** [comment]
I don't know why:

it is there
```r
> require(Stringendo)
Loading required package: Stringendo
> Stringendo::percentage_formatter()
```

Also, `export(percentage_formatter)` is in `~/GitHub/Packages/Stringendo/NAMESPACE`
