### ISSUE TITLE
rename error when use RenameGenesSeurat

### ISSUE THREAD

**Issue by songlyzz** [vertesy/Seurat.utils#69]
**Description**
Hi, vertesy:
  When I use the function of RenameGenesSeurat, I got some errors that :
RNA@data is of type dgeCMatrix!
Error in validObject(object = x) : 
  The object with the category "LogMap" is incorrect: Rownames cannot be empty strings
  
  Can you help me？I post my code below.

THANKS，
SONG

```R CODE
for (sample in folders ){ 
  sc_object <- CreateSeuratObject(
    counts = Read10X(file.path(sample), gene.column = 1),
    project = sample,
    min.cells = 3, min.features = 200
  )
  
  # rename 
  ids=mapIds(EnsDb.Mmusculus.v79,
             keys = rownames(sc_object), # the keys to select records for from the database.
             keytype="GENEID",
             columns="SYMBOL",
             column="SYMBOL")
  ids=as.data.frame(ids)
  ids$ENSEMBL=row.names(ids)
  ids=ids[!duplicated(ids$ids),]
  ids=ids[!duplicated(ids$ENSEMBL),]
  pos=match(ids$ENSEMBL,rownames(sc_object) )
  sc_object=sc_object[pos,]
  
  obj =RenameGenesSeurat(obj = sc_object,
                         newnames = ids$ids)
  sc_object<-obj[,-grep("NA",rownames(obj))]
}
```

**Comment by vertesy** [comment]
Hi Song, sure, happy to, 

could you please tell me your  version of: 
1. Seurat
2. Seurat.utils
3. the seurat version of `sc_object`.

This bug seems to be zombie: i solved it mutiple times, but keeps coming back

**Comment by vertesy** [comment]
great!

**Comment by songlyzz** [comment]
Hi vertesy,
  Now I have an another problem that in the org.Mm.eg.db, I did not have like "mt-" mitochondrial genes, how can I filter it when the name is not standard for PercentageFeatureSet(sc_object, pattern = "^mt-") function that in order to QC.

THANKS，
SONG

**Comment by vertesy** [comment]
I am sorry but this goes beyond what I can support. 
PercentageFeatureSet is anyways Seurat, not this package

**Comment by songlyzz** [comment]
Hi vertesy:
  Thank you very much! I know why my first method is not work, because here is a empty symbol gene name to match the ensembl id, but the org.Mm.eg.db database matches it, so the second one work well.
  I can fix them together to solve the problem.

THANKS，
SONG
