### ISSUE TITLE
plot3D.umap cause error on Seurat v5.1 object

### ISSUE THREAD

**Issue by Rohit-Satyam** [vertesy/Seurat.utils#86]
**Description**
I was trying to make a 3D UMAP but the function `plot3D.umap` complaints. I have all the reductions and since the error is not very informative, I can't resolve it on my own. 

...

**Buggy Behavior**
...

```r
plot3D.umap(category = "renamed_cluster", obj = integrated.without.tca)
category: renamed_cluster
annotate.by: renamed_cluster
Error in plot3D.umap(category = "renamed_cluster", obj = integrated.without.tca) : 
  reductions.backup is missing from @misc
> DefaultAssay(integrated.without.tca)
[1] "RNA"

```

![image](https://github.com/user-attachments/assets/eefbab25-d063-4376-9e61-770a107ee227)

**Comment by vertesy** [comment]
Hi!

as you can see in your image, your umap is 2D.

you need to run a 3D umap with `SetupReductionsNtoKdimensions()` that will backup both 2D and 3D umaps into `obj@misc$...` 
See `?SetupReductionsNtoKdimensions()` for usage.

**Comment by Rohit-Satyam** [comment]
Thanks the following worked. Just wanted to update.

```r
combined.obj <- SetupReductionsNtoKdimensions(obj = integrated.without.tca, nPCs = 30, dimensions = 2:3)
plot3D.umap(category = "original_phase", obj = combined.obj)
```
